### ISSUE TITLE
时区换算错误

### ISSUE THREAD

**Issue by CzarScar** [hollischuang/toBeTopJavaer#114]
[https://github.com/hollischuang/toBeTopJavaer/blob/master/docs/basics/java-basic/CET-UTC-GMT-CST.md](url)

这里最后关于时区的关系的描述中：

> 关系
CET=UTC/GMT + 1小时 CST=UTC/GMT +8 小时 CST=CET+9

CET=UTC/GMT + 1小时
CST=UTC/GMT + 8小时
CST=CET+7 才对吧？

**Comment by hollischuang** [comment]
感谢，已修复
