### ISSUE TITLE
敢问楼主成神了吗？

### ISSUE THREAD

**Issue by AibiTi** [hollischuang/toBeTopJavaer#18]
敢问楼主成神了吗？还 java 成神之路，白痴。

**Comment by mengxiaoyong** [comment]
傻叉


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by desirelll** [comment]
活得多卑微？戾气这么重

**Comment by java-aodeng** [comment]
哈哈

**Comment by stevenlii** [comment]
在封神榜的神仙体系里，神是死了后封的，仙才是生前封的(逃
