### ISSUE TITLE
【文字错误】第8章 字符串 

### ISSUE THREAD

**Issue by npzss** [hollischuang/toBeTopJavaer#188]
第110页，底部   在Class文件的常量池中共包含了Hollis、HollisChuang、Hol、lis666、Holl、s888这6个常量。
中的s888应为 is888

138页，底部代码
public int get(){
    int a = 1;
    try {
          retrurn a;
    }finally{
          a = 2;
          return a;
    }
}

这段代码结果应为2

141页 String[] strings = String[] strings = {}
这里写重复了

**Comment by hollischuang** [comment]
已在后续版本中修正，感谢勘误
