### ISSUE TITLE
Vector介绍是不是错了？

### ISSUE THREAD

**Issue by vanish1033** [hollischuang/toBeTopJavaer#193]
《深入理解java核心技术（基础篇）》152页的表10-1关于Vector的介绍，优点：适合查找   缺点：不适合查找，这里自相矛盾了，是不是写错了

**Comment by passerby660** [comment]
我也是看到这个,实在没忍住上来提的,之前都是给公众号提错

**Comment by hollischuang** [comment]
已在后续版本中修正，感谢勘误
