### ISSUE TITLE
如何学好Java，平衡工作和日常学习？

### ISSUE THREAD

**Issue by dear-Alice-moon** [hollischuang/toBeTopJavaer#3]
作者，你好。

    我自我介绍一下，我2017年夏季毕业，计算机科学与技术专业出身。在大学学的课程，几乎对编程没有任何用，都是皮毛。

    现在，我在亚信科技浙江杭州分部工作，目前我时常需要独自一人负责一个模块。公司中运用的技术非常的广泛，Dubbo、Spring Boot、Spring Cloud、IBatis、Spring、RocketMQ、Mysql、Oracle等等。我目前能力有限，只会写个增删查改。

    对  Dubbo、Spring Boot、Spring Cloud、IBatis、Spring、RocketMQ这些框架，只是懂一些最基本的皮毛，Mysql、Oracle这2个数据库也只是懂皮毛的知识。我深感自己对这些框架、数据库缺乏一个系统性的学习，我时常很苦恼。

   在工作中，自我去年8月入职到现在，一直加班到现在，时常工作都是996。平时很少有时间能够自学编程。小组内又缺乏Java开发工程师，除了我还有另外一位工程师。但是那位工程师不愿意探讨技术，日常技术交流、沟通也少。 

   目前，我感到学习编程技术好困难。一是每天可以用来自己自学的时间很少，二是现实生活中有没有可以相互探讨交流的人。目前，我自己的计划是，按顺序将Spring框架 ---> Mybatis框架  ---> SpringMVC框架  ---> SpringBoot框架  ---> Spring Cloud框架  ---> MQ 这些框架逐个学习过去。    

   昨天，另一位Java工程师让我处理Dubbo框架IP白名单的问题。今天，我的组长又让我去学习HBase，解决数据库表查询问题。面对多变的工作，我的学习计划不得不去调整！

   自2018年11月开始，我在W3CSchool上通过观看Spring在线文档，将Spring在线文档系统了学习了一遍。现在，我在看刘增辉老师编写《Mybatis从入门到精通》书籍，学习Mybatis。平时周六、周日不加班，我就在公司自学编程。

   本篇短文写的有些散乱，还望作者能够给些指点性意见。我该如何学好Java，并平衡好工作、生活，感谢。

**Comment by Michael728** [comment]
加油！我也同样有类似问题呢

**Comment by jamesxuhaozhe** [comment]
我自己在工作中也遇到这样的问题，我相信很多人都是这样。没有太多的解决方法，只能平时多挤时间学习了，并且制定一个清晰的学习方案。希望有所帮助

**Comment by dear-Alice-moon** [comment]
> 我自己在工作中也遇到这样的问题，我相信很多人都是这样。没有太多的解决方法，只能平时多挤时间学习了，并且制定一个清晰的学习方案。希望有所帮助

是的，共勉。

加油、加油，努力学习。

**Comment by cyl2cyl** [comment]
碎片化学习，先解决业务中的问题，不懂记下来，然后休息的时候研究

**Comment by dear-Alice-moon** [comment]
> 碎片化学习，先解决业务中的问题，不懂记下来，然后休息的时候研究

感谢回复，目前工作一直9106，休息的时间没有多少。 有点时间了，都忙着想去休息、睡觉了。
感谢您

**Comment by xuejianbest** [comment]
考虑换一下工作环境吧，否则时间浪费在不断重复“肤浅”的工作上，等年纪大了就更没有竞争力了。拒绝996，从我做起。

**Comment by AibiTi** [comment]
楼主学习能力不行，鉴定完毕。Mybatis 需要看书，看到文档和源码完事。

**Comment by jamesxuhaozhe** [comment]
建议楼主关闭issue吧
