### ISSUE TITLE
重载与重写

### ISSUE THREAD

**Issue by teleJa** [hollischuang/toBeTopJavaer#38]
重写的条件第二条:返回类型必须完全与被重写方法的返回类型相同；
返回重写方法的子类型也可以的

**Comment by songjiang951130** [comment]
可以算是类型相同，根据里氏替换原则，因为子类可以替换父类。

比如你要求返回的是一种鸟，你真实返回一只 鹦鹉 也行

**Comment by teleJa** [comment]
对的,close了
