### ISSUE TITLE
基本数据类型好像写错了

### ISSUE THREAD

**Issue by 1charon1** [hollischuang/toBeTopJavaer#39]
基本数据类型应该是8种吧，我看导航写的7种

**Comment by MrXionGe** [comment]
兄弟你很认真啊，我也发现了。导航写的7种，文章里面是对的，8种。

**Comment by Gamig0** [comment]
Java 有 8 种基本数据类型，但在《Thinking of Java》一书中，把 void 也算作一种基本数据类型，包装类 Void。在《码处高效》中，把引用变量(refvar)也算作一种基本数据类型。默认值为 null，存储 refobj 的首地址。

**Comment by MrXionGe** [comment]
@Gamig0 学院派
