### ISSUE TITLE
List<?>和List<Object>之间的区别是什么?这一节内容内容丢失

### ISSUE THREAD

**Issue by ForeverRoad** [hollischuang/toBeTopJavaer#66]
在线阅读里，内容丢失，跟绕口令一样

原文
List和List之间的区别是什么?
List 是一个未知类型的List，而List 其实是任意类型的List。你可以把List, List赋值给List，却不能把List赋值给 List。

**Comment by hollischuang** [comment]
谢谢提醒，已经修复
