### ISSUE TITLE
关于自动拆箱装箱的例子错误

### ISSUE THREAD

**Issue by gejaingbo** [hollischuang/toBeTopJavaer#72]
boolean flag = true;
    Integer i = 0;
    int j = 1;
    int k = flag ? i : j;
关于自动拆箱装箱的例子错误，这个例子并不会发生空指针异常，请作者留意下。

**Comment by PansonPanson** [comment]
Hollis的原文是这样说的：**如果这个时候i的值为null**，那么就会发生NPE。

> 很多人不知道，其实在int k = flag ? i : j;这一行，会发生自动拆箱。反编译后代码如下：

    boolean flag = true;
    Integer i = Integer.valueOf(0);
    int j = 1;
    int k = flag ? i.intValue() : j;
    System.out.println(k);
复制ErrorOK!
这其实是三目运算符的语法规范。当第二，第三位操作数分别为基本类型和对象时，其中的对象就会拆箱为基本类型进行操作。

因为例子中，flag ? i : j;片段中，第二段的i是一个包装类型的对象，而第三段的j是一个基本类型，所以会对包装类进行自动拆箱。如果这个时候i的值为null，那么就会发生NPE。
