### ISSUE TITLE
平台无关性的实现  这一小节中 “Java 16位系统”画成了  “61位系统”

### ISSUE THREAD

**Issue by zcx-git1240** [hollischuang/toBeTopJavaer#75]

**Comment by zcx-git1240** [comment]
http://hollischuang.gitee.io/tobetopjavaer/#/basics/object-oriented/platform-independent?id=%e4%bb%80%e4%b9%88%e6%98%af%e5%b9%b3%e5%8f%b0%e6%97%a0%e5%85%b3%e6%80%a7

**Comment by hollischuang** [comment]
已经修复
